import Head from "next/head";
import Link from "next/link";
import Footer from "../../components/main/Footer";
import ShotID from "../../components/shots/ShotID";

export default function item1() {
  return (
    <div className=" bg-neutral-900 min-h-screen h-full text-neutral-300 font-inter">
      <Head>
        <title>dribbbles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex pb-8 justify-center text-md px-8"></main>
      <ShotID url="/" name="item1" orig="eemeli" />
      <Footer />
    </div>
  );
}
