import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Footer from "../../components/main/Footer";
import ShotID from "../../components/shots/ShotID";

export default function moviecard() {
  return (
    <div className="subpixel-antialiased bg-neutral-900 min-h-screen h-full text-white font-satoshi">
      <Head>
        <title>dribbbles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen w-full h-full justify-center items-center">
        <div className="space-y-4">
          <main className="relative flex font-medium w-[256px] h-[380px] rounded-2xl overflow-hidden">
            <Image src="/posters/br2049.jpg" layout="fill" objectFit="cover" />
            <div className="sticky w-full h-full bg-gradient-to-tr from-black hover:opacity-75 transition duration-200"></div>
            <div className="absolute bottom-0 p-4">
              <div className="flex items-center space-x-2">
                <p className="font-lg">4,1</p>
                <div className="flex space-x-1">
                  <svg
                    width="14"
                    height="14"
                    viewBox="0 0 14 14"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M5.00932 4.80448L6.52455 1.75236C6.71903 1.36054 7.28101 1.36054 7.4755 1.75236L8.9907 4.80448L12.3792 5.29693C12.814 5.36011 12.9872 5.89148 12.6725 6.19627L10.221 8.57038L10.7996 11.9243C10.8739 12.355 10.4192 12.6835 10.0301 12.4801L7.00002 10.8957L3.96988 12.4801C3.58087 12.6835 3.12616 12.355 3.20045 11.9243L3.779 8.57038L1.32754 6.19627C1.01279 5.89148 1.18607 5.36011 1.62082 5.29693L5.00932 4.80448Z"
                      fill="white"
                      stroke="white"
                      stroke-width="1.5"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                  <svg
                    width="14"
                    height="14"
                    viewBox="0 0 14 14"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M5.00932 4.80448L6.52455 1.75236C6.71903 1.36054 7.28101 1.36054 7.4755 1.75236L8.9907 4.80448L12.3792 5.29693C12.814 5.36011 12.9872 5.89148 12.6725 6.19627L10.221 8.57038L10.7996 11.9243C10.8739 12.355 10.4192 12.6835 10.0301 12.4801L7.00002 10.8957L3.96988 12.4801C3.58087 12.6835 3.12616 12.355 3.20045 11.9243L3.779 8.57038L1.32754 6.19627C1.01279 5.89148 1.18607 5.36011 1.62082 5.29693L5.00932 4.80448Z"
                      fill="white"
                      stroke="white"
                      stroke-width="1.5"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                  <svg
                    width="14"
                    height="14"
                    viewBox="0 0 14 14"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M5.00932 4.80448L6.52455 1.75236C6.71903 1.36054 7.28101 1.36054 7.4755 1.75236L8.9907 4.80448L12.3792 5.29693C12.814 5.36011 12.9872 5.89148 12.6725 6.19627L10.221 8.57038L10.7996 11.9243C10.8739 12.355 10.4192 12.6835 10.0301 12.4801L7.00002 10.8957L3.96988 12.4801C3.58087 12.6835 3.12616 12.355 3.20045 11.9243L3.779 8.57038L1.32754 6.19627C1.01279 5.89148 1.18607 5.36011 1.62082 5.29693L5.00932 4.80448Z"
                      fill="white"
                      stroke="white"
                      stroke-width="1.5"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                  <svg
                    width="14"
                    height="14"
                    viewBox="0 0 14 14"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M5.00932 4.80448L6.52455 1.75236C6.71903 1.36054 7.28101 1.36054 7.4755 1.75236L8.9907 4.80448L12.3792 5.29693C12.814 5.36011 12.9872 5.89148 12.6725 6.19627L10.221 8.57038L10.7996 11.9243C10.8739 12.355 10.4192 12.6835 10.0301 12.4801L7.00002 10.8957L3.96988 12.4801C3.58087 12.6835 3.12616 12.355 3.20045 11.9243L3.779 8.57038L1.32754 6.19627C1.01279 5.89148 1.18607 5.36011 1.62082 5.29693L5.00932 4.80448Z"
                      fill="white"
                      stroke="white"
                      stroke-width="1.5"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                </div>
              </div>
              <p className="text-2xl font-bold">Blade Runner 2049</p>
              <p className="text-lg">2017</p>
            </div>
          </main>
          <div className="flex justify-center space-x-4">
            <button className="group flex bg-[#F8E4DC] px-8 py-1 rounded-2xl">
              <div className="group-hover:scale-125 transition duration-150">
                <svg
                  width="48"
                  height="48"
                  viewBox="0 0 48 48"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M24 24L32 32M16 32L24 24L16 32ZM32 16L24 24L32 16ZM24 24L16 16L24 24Z"
                    stroke="#FF7777"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </svg>
              </div>
            </button>
            <button className="group flex bg-[#FF7777] px-8 py-1 rounded-2xl">
              <div className="group-hover:scale-125 transition duration-150">
                <svg
                  width="48"
                  height="48"
                  viewBox="0 0 48 48"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M33.76 20.6529C33.76 22.3025 33.114 23.8869 31.9602 25.059C29.3045 27.7578 26.7287 30.572 23.9738 33.1729C23.3423 33.7604 22.3406 33.739 21.7363 33.1249L13.7993 25.059C11.4002 22.6209 11.4002 18.6849 13.7993 16.2469C16.2219 13.7849 20.1686 13.7849 22.5912 16.2469L22.8798 16.5401L23.1681 16.2471C24.3297 15.066 25.9116 14.3999 27.5642 14.3999C29.2167 14.3999 30.7986 15.066 31.9602 16.2469C33.1141 17.419 33.76 19.0034 33.76 20.6529Z"
                    fill="#FAFAFA"
                  />
                </svg>
              </div>
            </button>
          </div>
          <div className="flex justify-center text-neutral-600">
            <button className="hover:text-neutral-400 transition duration-150">
              Go back
            </button>
          </div>
        </div>
      </div>
      <ShotID
        url="/shots/moviecard"
        userurl="/shots/moviecard"
        name="moviecard"
        orig="eemeli"
      />
      <Footer />
    </div>
  );
}
