import Head from "next/head";
import Link from "next/link";
import Footer from "../../components/main/Footer";
import ShotID from "../../components/shots/ShotID";

export default function item1() {
  return (
    <div className="subpixel-antialiased bg-neutral-900 min-h-screen h-full text-neutral-300 font-satoshi">
      <Head>
        <title>dribbbles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen w-full h-full justify-center items-center p-8">
        <main className="w-full max-w-[640px] font-medium text-lg">
          <div className="text-black tracking-tight">
            <div className="rounded-3xl sm:p-8 px-8 py-12 space-y-8 bg-white">
              <div className="space-y-2">
                <p className="font-bold text-2xl">Blade Runner 2049</p>
                <p className="text-base text-neutral-700">
                  2017, Directed by Denis Villeneuve
                </p>
              </div>
              <p className="">
                Thirty years after the events of the first film, a new blade
                runner, LAPD Officer K, unearths a long-buried secret that has
                the potential to plunge what’s left of society into chaos. K’s
                discovery leads him on a quest to find Rick Deckard, a former
                LAPD blade runner who has been missing for 30 years.
              </p>
              <div className="md:flex md:space-y-0 items-center space-y-4">
                <div className="flex w-full justify-center space-x-2">
                  <div className="px-4 h-8 rounded-full bg-neutral-200 flex space-x-2 items-center">
                    <p>4,1</p>
                    <div className="flex">
                      <svg
                        width="14"
                        height="14"
                        viewBox="0 0 14 14"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M5.00932 4.80448L6.52455 1.75236C6.71903 1.36054 7.28101 1.36054 7.4755 1.75236L8.9907 4.80448L12.3792 5.29693C12.814 5.36011 12.9872 5.89148 12.6725 6.19627L10.221 8.57038L10.7996 11.9243C10.8739 12.355 10.4192 12.6835 10.0301 12.4801L7.00002 10.8957L3.96988 12.4801C3.58087 12.6835 3.12616 12.355 3.20045 11.9243L3.779 8.57038L1.32754 6.19627C1.01279 5.89148 1.18607 5.36011 1.62082 5.29693L5.00932 4.80448Z"
                          fill="black"
                          stroke="black"
                          stroke-width="1.5"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        />
                      </svg>
                      <svg
                        width="14"
                        height="14"
                        viewBox="0 0 14 14"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M5.00932 4.80448L6.52455 1.75236C6.71903 1.36054 7.28101 1.36054 7.4755 1.75236L8.9907 4.80448L12.3792 5.29693C12.814 5.36011 12.9872 5.89148 12.6725 6.19627L10.221 8.57038L10.7996 11.9243C10.8739 12.355 10.4192 12.6835 10.0301 12.4801L7.00002 10.8957L3.96988 12.4801C3.58087 12.6835 3.12616 12.355 3.20045 11.9243L3.779 8.57038L1.32754 6.19627C1.01279 5.89148 1.18607 5.36011 1.62082 5.29693L5.00932 4.80448Z"
                          fill="black"
                          stroke="black"
                          stroke-width="1.5"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        />
                      </svg>
                      <svg
                        width="14"
                        height="14"
                        viewBox="0 0 14 14"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M5.00932 4.80448L6.52455 1.75236C6.71903 1.36054 7.28101 1.36054 7.4755 1.75236L8.9907 4.80448L12.3792 5.29693C12.814 5.36011 12.9872 5.89148 12.6725 6.19627L10.221 8.57038L10.7996 11.9243C10.8739 12.355 10.4192 12.6835 10.0301 12.4801L7.00002 10.8957L3.96988 12.4801C3.58087 12.6835 3.12616 12.355 3.20045 11.9243L3.779 8.57038L1.32754 6.19627C1.01279 5.89148 1.18607 5.36011 1.62082 5.29693L5.00932 4.80448Z"
                          fill="black"
                          stroke="black"
                          stroke-width="1.5"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        />
                      </svg>
                      <svg
                        width="14"
                        height="14"
                        viewBox="0 0 14 14"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M5.00932 4.80448L6.52455 1.75236C6.71903 1.36054 7.28101 1.36054 7.4755 1.75236L8.9907 4.80448L12.3792 5.29693C12.814 5.36011 12.9872 5.89148 12.6725 6.19627L10.221 8.57038L10.7996 11.9243C10.8739 12.355 10.4192 12.6835 10.0301 12.4801L7.00002 10.8957L3.96988 12.4801C3.58087 12.6835 3.12616 12.355 3.20045 11.9243L3.779 8.57038L1.32754 6.19627C1.01279 5.89148 1.18607 5.36011 1.62082 5.29693L5.00932 4.80448Z"
                          fill="black"
                          stroke="black"
                          stroke-width="1.5"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        />
                      </svg>
                    </div>
                  </div>
                  <div className="px-4 h-8 rounded-full bg-neutral-200 flex space-x-2 items-center">
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 16 16"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M8.00002 9.33317C8.73642 9.33317 9.33335 8.73624 9.33335 7.99984C9.33335 7.26344 8.73642 6.6665 8.00002 6.6665C7.26362 6.6665 6.66669 7.26344 6.66669 7.99984C6.66669 8.73624 7.26362 9.33317 8.00002 9.33317Z"
                        stroke="black"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      />
                      <path
                        d="M14 8C12.7409 9.994 10.4789 12 8 12C5.52113 12 3.25904 9.994 2 8C3.53237 6.1055 5.32775 4 8 4C10.6723 4 12.4677 6.10547 14 8Z"
                        stroke="black"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      />
                    </svg>
                    <p>812k</p>
                  </div>
                  <div className="px-4 h-8 rounded-full bg-neutral-200 flex space-x-2 items-center">
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 16 16"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M14.6666 5.90815C14.6666 6.93913 14.2708 7.9294 13.5638 8.66193C11.9366 10.3487 10.3582 12.1075 8.67018 13.7331C8.28324 14.1003 7.66944 14.0869 7.29918 13.7031L2.43582 8.66193C0.965811 7.13813 0.965811 4.67815 2.43582 3.15438C3.92027 1.61563 6.3386 1.61563 7.82304 3.15438L7.99984 3.33761L8.17651 3.15449C8.88824 2.41633 9.85758 2 10.8702 2C11.8828 2 12.852 2.41629 13.5638 3.15438C14.2708 3.88697 14.6666 4.87718 14.6666 5.90815Z"
                        fill="black"
                        stroke="black"
                        stroke-width="1.5"
                        stroke-linejoin="round"
                      />
                    </svg>

                    <p>306k</p>
                  </div>
                </div>
                <div className="w-full flex md:justify-end justify-center">
                  <div className="bg-black flex justify-center items-center px-8 rounded-2xl p-4">
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M4 12.8571L8.57143 17.4286L20 6"
                        stroke="white"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      />
                    </svg>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
      <ShotID
        url="/shots/lettucewatch"
        userurl="/shots/lettucewatch"
        name="movieinfo"
        orig="eemeli"
      />
      <Footer />
    </div>
  );
}
