import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Footer from "../../components/main/Footer";
import ShotID from "../../components/shots/ShotID";

export default function sessionselect() {
  return (
    <div className="subpixel-antialiased bg-neutral-0 min-h-screen h-full text-black font-satoshi tracking-tight text-xl">
      <Head>
        <title>dribbbles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center">
        <div className="py-8 flex flex-col justify-between h-screen">
          <div className=" flex justify-center">
            <p className="text-3xl">🥬 Lettucewatch</p>
          </div>
          <div className="space-y-4">
            <div className="flex justify-center">
              <button className="flex justify-center items-center space-x-4 bg-green-200 px-16 py-4 rounded-2xl group hover:bg-green-300 transition duration-150">
                <p className="pb-1">Generate session</p>
                <div className="group-hover:translate-x-2 transition duration-150 scale-125">
                  <svg
                    width="19"
                    height="18"
                    viewBox="0 0 19 18"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M17.6667 9L9.66667 17M1 9H17.6667H1ZM17.6667 9L9.66667 1L17.6667 9Z"
                      stroke="black"
                      stroke-width="1.5"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                </div>
              </button>
            </div>
            <div className="flex justify-center">
              <button className="flex items-center space-x-4 bg-orange-200 px-16 py-4 rounded-2xl group hover:bg-orange-300 transition duration-150">
                <p className="pb-1">Join session</p>
                <div className="group-hover:translate-x-2 transition duration-150 scale-125">
                  <svg
                    width="19"
                    height="18"
                    viewBox="0 0 19 18"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M17.6667 9L9.66667 17M1 9H17.6667H1ZM17.6667 9L9.66667 1L17.6667 9Z"
                      stroke="black"
                      stroke-width="1.5"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                </div>
              </button>
            </div>
          </div>
          <div className="space-y-4">
            <p className="text-base text-center text-neutral-500">
              logged in as:
              <br />
              eemeli
            </p>
            <div className="flex justify-center">
              <button className="flex items-center space-x-4 bg-red-300 px-12 py-2 rounded-xl group hover:bg-red-400 transition duration-150">
                <p className="pb-1">Log out</p>
                <div className="group-hover:translate-x-2 transition duration-150 scale-125">
                  <svg
                    width="15"
                    height="18"
                    viewBox="0 0 15 18"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M13.4446 8.99999L10.7779 6.33333M7.22235 8.99999H13.4446H7.22235ZM13.4446 8.99999L10.7779 11.6667L13.4446 8.99999Z"
                      stroke="black"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                    <path
                      d="M13.4444 3.66667V2.77778C13.4444 1.79594 12.6485 1 11.6667 1H2.77778C1.79594 1 1 1.79594 1 2.77778V15.2222C1 16.2041 1.79594 17 2.77778 17H11.6667C12.6485 17 13.4444 16.2041 13.4444 15.2222V14.3333"
                      stroke="black"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
