import Head from "next/head";
import Link from "next/link";
import Footer from "../components/main/Footer";
import Rings from "../components/main/Rings";
import ShotsItem from "../components/shots/ShotsItem";

export default function Shots() {
  return (
    <div className=" bg-neutral-900 min-h-screen h-full text-neutral-300 font-inter">
      <Head>
        <title>dribbbles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex pb-8 justify-center text-md px-8">
        <div className="my-16 z-10 max-w-[40rem] rounded-3xl space-y-8 w-screen px-8 py-16 bg-black/[0.25] backdrop-blur-md">
          <div className="flex text-neutral-500">
            <p className="text-5xl sm:text-8xl font-semibold tracking-tighter">
              Dribbbles
            </p>
            <p>/shots</p>
          </div>
          <div className="space-y-4">
            <ShotsItem
              name="item1"
              orig="eemeli"
              url="/"
              shoturl="/shots/item1"
            />
            <ShotsItem name="something" orig="someone" url="/" shoturl="/" />
            <ShotsItem name="something" orig="someone" url="/" shoturl="/" />
            <ShotsItem name="something" orig="someone" url="/" shoturl="/" />
            <ShotsItem name="something" orig="someone" url="/" shoturl="/" />
            <ShotsItem name="something" orig="someone" url="/" shoturl="/" />
            <ShotsItem name="something" orig="someone" url="/" shoturl="/" />
          </div>
        </div>
        <Rings />
      </main>
      <Footer />
    </div>
  );
}
